---
- name: Pull Docker Image of Calculator
  hosts: myHosts
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Install Kubernetes Python module
      pip:
        name: kubernetes
        state: present
        executable: pip3

    - name: Apply frontend deployment
      k8s:
        state: present
        src: "./k8s_configs/frontend-deployment.yaml"
        kubeconfig: "/home/ricky/.kube/config"

    - name: Apply frontend service
      k8s:
        state: present
        src: "./k8s_configs/frontend-service.yaml"
        kubeconfig: "/home/ricky/.kube/config"
