---
- name: Pull Docker Image of Calculator
  hosts: myHosts
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started
