apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rricky25/backend_image
        env:
        - name: ENV_VAR_NAME
          value: "value"
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DB_URL
        - name: JWT_SECRET_KEY 
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET_KEY
        command: ["/bin/sh", "-c"]
        args:
        - ls && pwd && npm run start;
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: backend-logs
            mountPath: /backend/logs
      volumes:
        - name:  backend-logs
          hostPath:
            path: /var/log/backend/app
            type: DirectoryOrCreate
