- name: Create backend secrets in Kubernetes
  kubernetes.core.k8s:
    kubeconfig: "~/.kube/config"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: backend-secrets
        namespace: default
      type: Opaque
      data:
        DB_URL: "{{ DB_URL | b64encode }}"
        JWT_SECRET_KEY: "{{ JWT_SECRET_KEY | b64encode }}"

# Apply Kubernetes Manifests for Backend. webhook testing.
- name: Apply backend deployment and service
  kubernetes.core.k8s:
    kubeconfig: "~/.kube/config"
    state: present
    definition: "{{ lookup('file', '../backend.yaml') }}"

- name: Wait for elk service to be ready
  shell: |
    kubectl wait --for=condition=available --timeout=300s deployment/backend
  register: wait_result
  changed_when: false

- name: Wait for 10 seconds for all the services to setup
  pause:
    seconds: 10

# Port-forward the frontend service to make it accessible on port 5173
- name: Port-forward backend service
  command: kubectl port-forward service/backend-service 5000:5000
  async: 7200 # Run the command asynchronously
  poll: 0
