- name: Create frontend secrets in Kubernetes
  kubernetes.core.k8s:
    kubeconfig: "~/.kube/config"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: frontend-secrets
        namespace: default
      type: Opaque
      data:
        VITE_API_KEY: "{{ VITE_API_KEY | b64encode }}"
        VITE_Auth_Domain: "{{ VITE_Auth_Domain | b64encode }}"
        VITE_PROJECT_ID: "{{ VITE_PROJECT_ID | b64encode }}"
        VITE_STORAGE_BUCKET: "{{ VITE_STORAGE_BUCKET | b64encode }}"
        VITE_MESSAGING_SENDERID: "{{ VITE_MESSAGING_SENDERID | b64encode }}"
        VITE_APPID: "{{ VITE_APPID | b64encode }}"
        VITE_MEASUREMENT_ID: "{{ VITE_MEASUREMENT_ID | b64encode }}"
        VITE_BACKEND_BASEURL: "{{ VITE_BACKEND_BASEURL | b64encode }}"

# Apply Kubernetes Manifests for Frontend
- name: Apply frontend deployment and service
  kubernetes.core.k8s:
    kubeconfig: "~/.kube/config"
    state: present
    definition: "{{ lookup('file', '../frontend.yaml') }}"

- name: Wait for frontend service to be ready
  shell: |
    kubectl wait --for=condition=available --timeout=300s deployment/frontend-deployment
  register: wait_result
  changed_when: false

- name: Wait for 10 seconds for all the services to setup
  pause:
    seconds: 10

# Port-forward the frontend service to make it accessible on port 5173 hello testing
- name: Port-forward frontend service
  command: kubectl port-forward service/frontend-service 5173:5173
  async: 300 # Run the command asynchronously (for 10 min)
  poll: 0 # Don't wait for the task to complete; it's running in the background
