# Apply Kubernetes Manifests for elk-stack
- name: Apply elk-stack deployment
  kubernetes.core.k8s:
    kubeconfig: "~/.kube/config"
    state: present
    definition: "{{ lookup('file', '../elk.yaml') }}"

- name: Wait for elk service to be ready
  shell: |
    kubectl wait --for=condition=available --timeout=300s deployment/elk-stack
  register: wait_result
  changed_when: false

- name: Wait for 10 seconds for all the services to setup
  pause:
    seconds: 10

# Port-forward the elk service to make it accessible on port 9200
- name: Port-forward elk elasticserch related service
  command: kubectl port-forward service/elk-stack-service 9200:9200
  async: 800 # Run the command asynchronously (for 10 min)
  poll: 0 # Don't wait for the task to complete; it's running in the background

# Port-forward the elk service to make it accessible on port 5601
- name: Port-forward elk kibana related service
  command: kubectl port-forward service/elk-stack-service 5601:5601
  async: 800 # Run the command asynchronously (for 10 min)
  poll: 0 # Don't wait for the task to complete; it's running in the background
